name: Update Firebase Referrals

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  update-referrals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install firebase-admin

      - name: Update referrals in Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > serviceAccountKey.json
          node updateReferrals.js
